In [69]:
import pandas as pd
df = pd.read_csv('movies.csv')
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [70]:
df.industry.unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [71]:
df.language.unique()
df[df.language == 'Telugu'].head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [72]:
df.industry.value_counts()

industry
Hollywood    20
Bollywood    17
Name: count, dtype: int64

In [73]:
df.language.value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [74]:
df[['title','release_year','imdb_rating']]

                                          title  release_year  imdb_rating
0                               Pather Panchali          1955          8.3
1   Doctor Strange in the Multiverse of Madness          2022          7.0
2                         Thor: The Dark World           2013          6.8
3                               Thor: Ragnarok           2017          7.9
4                       Thor: Love and Thunder           2022          6.8
5                      The Shawshank Redemption          1994          9.3
6                                  Interstellar          2014          8.6
7                      The Pursuit of Happyness          2006          8.0
8                                     Gladiator          2000          8.5
9                                       Titanic          1997          7.9
10                        It's a Wonderful Life          1946          8.6
11                                       Avatar          2009          7.8
12                                The Godfather          1972          9.2
13                              The Dark Knight          2008          9.0
14                             Schindler's List          1993          9.0
15                                Jurassic Park          1993          8.2
16                                     Parasite          2019          8.5
17                            Avengers: Endgame          2019          8.4
18                       Avengers: Infinity War          2018          8.4
19           Captain America: The First Avenger          2011          6.9
20          Captain America: The Winter Soldier          2014          7.8
21                  Dilwale Dulhania Le Jayenge          1995          8.0
22                                     3 Idiots          2009          8.4
23                     Kabhi Khushi Kabhie Gham          2001          7.4
24                             Bajirao Mastani           2015          7.2
25                             Taare Zameen Par          2007          8.3
26                          Munna Bhai M.B.B.S.          2003          8.1
27                                           PK          2014          8.1
28                                        Sanju          2018          NaN
29                            The Kashmir Files          2022          8.3
30                            Bajrangi Bhaijaan          2015          8.1
31                                       Race 3          2018          1.9
32                                    Shershaah          2021          8.4
33                             K.G.F: Chapter 2          2022          8.4
34                    Pushpa: The Rise - Part 1          2021          7.6
35                                          RRR          2022          8.0
36                     Baahubali: The Beginning          2015          8.0

In [75]:
df.release_year>2000
df[(df.release_year>2000) & (df.release_year<=2010)]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [76]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     object
 1   industry      37 non-null     object
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     object
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     object
 8   currency      37 non-null     object
 9   language      37 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 3.0+ KB

In [78]:
df[(df.imdb_rating == df.imdb_rating.max()) | (df.imdb_rating == df.imdb_rating.min()) ]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [79]:
df['age'] = df['release_year'].apply(lambda x: 2024 - x)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,69
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,2
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,11
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,7
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,2
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,30
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,10
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,18
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,24
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,27
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,78
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,15
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,52
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,16
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,31
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,31
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,5
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,5
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,6
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,13
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,10
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,29
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,15
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,23
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,9
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,17
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,21
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,10
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,6
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,2
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,9
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,6
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,3
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,2
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,3
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,2
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,9

In [80]:
df['profit'] = df.apply(lambda x: x['revenue'] - x['budget'], axis=1)
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,69,30000.00
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,2,754.80
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,11,479.80
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,7,674.00
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,2,420.00
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,30,48.30
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,10,536.80
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,18,252.10
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,24,357.50
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,27,2002.00
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,78,0.12
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,15,2610.00
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,52,283.80
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,16,821.00
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,31,300.20
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,31,983.00
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,5,247.60
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,5,2398.00
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,6,1648.00
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,13,153.90
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,10,537.40
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,29,1600.00
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,15,3450.00
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,23,970.00
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,9,2.10
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,17,1230.00
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,21,310.00
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,10,7690.00
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,6,4.90
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,2,3159.00
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,9,10790.00
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,6,1.30
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,3,450.00
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,2,11.50
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,3,1.60
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,2,6.50
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,9,4.70

In [81]:
df.index

RangeIndex(start=0, stop=37, step=1)

In [82]:
df.set_index('title',inplace=True)

In [83]:
df.head()

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,69,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,2,754.8
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,11,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,7,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,2,420.0

In [84]:
df.index

Index(['Pather Panchali', 'Doctor Strange in the Multiverse of Madness',
       'Thor: The Dark World ', 'Thor: Ragnarok ', 'Thor: Love and Thunder ',
       'The Shawshank Redemption', 'Interstellar', 'The Pursuit of Happyness',
       'Gladiator', 'Titanic', 'It's a Wonderful Life', 'Avatar',
       'The Godfather', 'The Dark Knight', 'Schindler's List', 'Jurassic Park',
       'Parasite', 'Avengers: Endgame', 'Avengers: Infinity War',
       'Captain America: The First Avenger',
       'Captain America: The Winter Soldier', 'Dilwale Dulhania Le Jayenge',
       '3 Idiots', 'Kabhi Khushi Kabhie Gham', 'Bajirao Mastani ',
       'Taare Zameen Par', 'Munna Bhai M.B.B.S.', 'PK', 'Sanju',
       'The Kashmir Files', 'Bajrangi Bhaijaan', 'Race 3', 'Shershaah',
       'K.G.F: Chapter 2', 'Pushpa: The Rise - Part 1', 'RRR',
       'Baahubali: The Beginning'],
      dtype='object', name='title')

In [85]:
df.loc['RRR']

industry                Bollywood
release_year                 2022
imdb_rating                   8.0
studio          DVV Entertainment
budget                        5.5
revenue                      12.0
unit                     Billions
currency                      INR
language                   Telugu
age                             2
profit                        6.5
Name: RRR, dtype: object

In [86]:
df.loc[['RRR', 'Sanju']]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,profit
title,,,,,,,,,,,
RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu,2,6.5
Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.0,5.9,Billions,INR,Hindi,6,4.9

Since the index changed from int to string, we cannot do d[0] any more instead:

In [87]:
df.iloc[0]

industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
age                                    69
profit                            30000.0
Name: Pather Panchali, dtype: object